// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4JksRaDCpgNRUTO0a6w4GyRTR8hTeQy0',
    appId: '1:812209498110:web:d7ea68e06b7408d22402af',
    messagingSenderId: '812209498110',
    projectId: 'onthepresent-216c0',
    authDomain: 'onthepresent-216c0.firebaseapp.com',
    storageBucket: 'onthepresent-216c0.firebasestorage.app',
    measurementId: 'G-4KWRB8B15T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHK68ocXOPCZmcrVIqNWRdPOy6J-rVrA',
    appId: '1:812209498110:android:06e996c3381431882402af',
    messagingSenderId: '812209498110',
    projectId: 'onthepresent-216c0',
    storageBucket: 'onthepresent-216c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXLAwGE0ka7M_QgX3Z0eynIzTxEbyKOWQ',
    appId: '1:812209498110:ios:f5d38bde9bfc96ba2402af',
    messagingSenderId: '812209498110',
    projectId: 'onthepresent-216c0',
    storageBucket: 'onthepresent-216c0.firebasestorage.app',
    iosBundleId: 'com.example.onthepresent',
  );
}
